// Code generated by "stringer -type=RyzenFamily"; DO NOT EDIT.

package lib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WAIT_FOR_LOAD - -2]
	_ = x[UNKNOWN - -1]
	_ = x[RAVEN-0]
	_ = x[PICASSO-1]
	_ = x[RENOIR-2]
	_ = x[CEZANNE-3]
	_ = x[DALI-4]
	_ = x[LUCIENNE-5]
	_ = x[VANGOGH-6]
	_ = x[REMBRANDT-7]
	_ = x[MENDOCINO-8]
	_ = x[PHOENIX-9]
	_ = x[HAWKPOINT-10]
	_ = x[STRIXPOINT-11]
	_ = x[END-12]
}

const _RyzenFamily_name = "WAIT_FOR_LOADUNKNOWNRAVENPICASSORENOIRCEZANNEDALILUCIENNEVANGOGHREMBRANDTMENDOCINOPHOENIXHAWKPOINTSTRIXPOINTEND"

var _RyzenFamily_index = [...]uint8{0, 13, 20, 25, 32, 38, 45, 49, 57, 64, 73, 82, 89, 98, 108, 111}

func (i RyzenFamily) String() string {
	i -= -2
	if i < 0 || i >= RyzenFamily(len(_RyzenFamily_index)-1) {
		return "RyzenFamily(" + strconv.FormatInt(int64(i+-2), 10) + ")"
	}
	return _RyzenFamily_name[_RyzenFamily_index[i]:_RyzenFamily_index[i+1]]
}
